name: Backup to Google Drive

on:
  schedule:
    - cron: '0 3 * * 0' # Backup jeden Sonntag um 03:00 Uhr
  workflow_dispatch: # Erlaubt manuelles Starten per Button

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Archiv erstellen
        run: |
          tar --exclude="all-repos-backup-*.tar.gz" -czf all-repos-backup-$(date +%F).tar.gz all-github-backups/

      - name: Rclone installieren
        run: sudo apt-get install -y rclone

      - name: Rclone konfigurieren & Upload starten
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$GDRIVE_SA_JSON" > /tmp/sa.json
          
          cat <<EOF > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          scope = drive
          service_account_file = /tmp/sa.json
          root_folder_id = $FOLDER_ID
          EOF
          
          rclone copy github-backup-*.tar.gz gdrive:
